export interface CalculationUC {
  id: number;
  label: string;
  selectedStandardPrepLabel: string | null;
  selectedSamplePrepLabel: string | null;
  areaOfStandard: string | null;
  areaOfSample1: string | null;
  areaOfSample2: string | null;
  areaOfSample3: string | null;
  areaOfSample4: string | null;
  areaOfSample5: string | null;
  areaOfSample6: string | null;
  areaOfSample7: string | null;
  areaOfSample8: string | null;
  areaOfSample9: string | null;
  areaOfSample10: string | null;
  purity: string;
  mWBase: string;
  mWSalt: string;
  calculationResult: string | null;
  calculationResultUnit: string | null;
  calculationResultTablet1: string | null;
  calculationResultTablet2: string | null;
  calculationResultTablet3: string | null;
  calculationResultTablet4: string | null;
  calculationResultTablet5: string | null;
  calculationResultTablet6: string | null;
  calculationResultTablet7: string | null;
  calculationResultTablet8: string | null;
  calculationResultTablet9: string | null;
  calculationResultTablet10: string | null;
  sw1: string | null;
  claim: string | null;
  dilutedVol: string | null;
  v1: string | null;
  v2: string | null;
  v3: string | null;
  v4: string | null;
  v5: string | null;
  v6: string | null;
  v7: string | null;
  v8: string | null;
  v9: string | null;
  v10: string | null;
  v11: string | null;
  v12: string | null;
  v13: string | null;
  v14: string | null;
  v15: string | null;
  v16: string | null;
}